AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Configure SNS topic as event source for Lambda function

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function that has the MyTopic SNS topic as event source
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
